### ISSUE TITLE
Typo in restore script command call in documentation

### ISSUE THREAD

**Issue by caosborne89** [ManifoldScholar/manifold-docusaurus#149]
I believe this line [here](https://github.com/ManifoldScholar/manifold-docusaurus/blob/7091e1dd7a8bda42351ae0f5b3c9d485ad0fd07b/docs/administering/backup_restore.md?plain=1#L139) is incorrect. Pretty sure it should be:

```
./manifold-restore.sh manifold-backup-11-17-20-1605640139.tar
```
Small change, but should probably be fixed.

**Comment by zdavis** [comment]
Thank you! Fixed in 91fb4cf676a7d36dc88b6699da6461170b824ce8
