### ISSUE TITLE
Script provided for restore should have checks for unprovided back up files

### ISSUE THREAD

**Issue by caosborne89** [ManifoldScholar/manifold-docusaurus#150]
The script provided in the documentation [here](https://github.com/ManifoldScholar/manifold-docusaurus/blob/7091e1dd7a8bda42351ae0f5b3c9d485ad0fd07b/docs/administering/backup_restore.md?plain=1#L153) should include a check for missing backup files (for the tar file user provided in the argument, the dump.sql inside the tar file, and probably the uploads file in the tar file as well). I know it's just a script provided in documentation, but if someone uses this script and accidentally doesn't provide the backup files the database will drop before trying to restore from the file that doesn't exist. Asking for a friend.

**Comment by zdavis** [comment]
I hope your friend forgives the oversight :) — I'll try to clean it up this week.

**Comment by zdavis** [comment]
Fixed in 43213c4e50b10589af0c1abb00763b25d9c1aa8b
