### ISSUE TITLE
Adjust nav item margins

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold-docusaurus#87]
I think we need a few more pixels between these fellas:
![image](https://user-images.githubusercontent.com/255909/119568594-77d7ad00-bd62-11eb-898c-1a825325e5e6.png)

So the margins are more like this:
![image](https://user-images.githubusercontent.com/255909/119568641-8d4cd700-bd62-11eb-8e71-4857b6b154e9.png)

**Comment by jen-castiron** [comment]
Fixed in this commit: https://github.com/ManifoldScholar/manifold-docusaurus/commit/35a93077a12ff9756d471c3018e6153a6f04f4ee
